const listOfBadWordsNotAllowed = [
    'sex',
    'porn',
    'fuck',
    'cock',
    'titties',
    'boner',
    'muff',
    'pussy',
    'asshole',
    'cunt',
    'ass',
    'cockfoam',
    'nigger',
    'arse',
    'arsehole',
    'as useful as tits on a bull',
    'balls',
    'bastard',
    'beaver',
    'bellend',
    'berk',
    'bitch',
    'bollocks',
    'bukkake',
    'bullshit',
    'cack',
    'cad',
    'chav',
    'cock cheese',
    'cock jockey',
    'cock - up',
    'cocksucker',
    'cockwomble',
    'cunt',
    'dick',
    'dickhead',
    'dildo',
    'fuck',
    'fucking cunt',
    'fucktard',
    'gash',
    'hobknocker',
    'motherfucker',
    'munter',
    'muppet',
    'naff',
    'prick',
    'pussy',
    'randy',
    'rapey',
    'rat arsed',
    'shit',
    'shite',
    'shitfaced',
    'skank',
    'slag',
    'slapper',
    'slut',
    'son of a bitch',
    'spunk',
    'swine',
    'taking the piss',
    'tits',
    'twat',
    'twonk',
    'u fukin wanker',
    'wally',
    'wanker',
    'wankstain',
    'wazzack',
    'whore',
];

export default listOfBadWordsNotAllowed;
